Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -127,19 +127,10 @@ runs:
       shell: bash
       if: ${{ inputs.force != 'true' }}
       run: |
-        # Convert DD/MM/YYYY to YYYY-MM-DD
-        if [[ "$DATE" =~ ^[0-9]{2}/[0-9]{2}/[0-9]{4}$ ]]; then
-          DATE=$(echo "$DATE" | awk -F/ '{print $3"-"$2"-"$1}')
-        fi
-        
-        TODAY=$(date +%Y-%m-%d)
-        YESTERDAY=$(date -d "yesterday" +%Y-%m-%d)
-        TOMORROW=$(date -d "tomorrow" +%Y-%m-%d)
-
-        if [[ "$DATE" != "$TODAY" && "$DATE" != "$YESTERDAY" && "$DATE" != "$TOMORROW" ]]; then
-          echo "::error::Date found in PackageInfo.g ($DATE) does not match current date ($TODAY) up to ±1 day."
+        $GITHUB_ACTION_PATH/check_date.sh $DATE || {
+          echo "::error::Date found in PackageInfo.g ($DATE) does not match current date ($(date +%Y-%m-%d)) up to ±1 day."
           exit 1
-        fi
+        }
 
     # We make a copy of the current directory to build the release from, because
     # the next step will remove files/folders that may be necessary for subsequent
