Add sanity check for absolute paths (#48)
* Check for absolute paths

* Don't error if grep didn't match any files

* Update .github/workflows/CI.yml

Co-authored-by: Max Horn <max@quendi.de>

---------

Co-authored-by: Max Horn <max@quendi.de>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -23,6 +23,14 @@ runs:
       shell: bash
       run: |
         gap -A -q -c 'QuitGap(ValidatePackageInfo("PackageInfo.g"));'
+        
+    - name: "Check documentation for absolute paths"
+      shell: bash
+      run: |
+        $GITHUB_ACTION_PATH/check_absolute_paths.sh || {
+          echo "::error::Found absolute paths in HTML file(s)"
+          exit 1
+        }
 
     - name: "Create assets folder"
       shell: bash
