Finish a first "proper" version of the action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,8 +1,14 @@
 ---
-name: "Prepare an archive tarball"
-description: "Be aware that the only responsibility of this repository is validation and archive tarball preparation."
+name: "Release GAP package"
+description: "Makes a release of the GAP package on GitHub, with archives and manuals as assets"
 icon: "archive"
 color: "black"
+
+inputs:
+  dry-run:
+    description: "Set to true to not push the release to GitHub"
+    required: false
+    default: "false"
 
 runs:
   using: "composite"
@@ -11,21 +17,28 @@ runs:
       shell: bash
       run: |
         set -e
+        
+        echo "::group:: Validating PackageInfo.g"
         gap -A -q -c 'QuitGap(ValidatePackageInfo("PackageInfo.g"));'
 
     - name: "Generate package-info.json"
       shell: bash
       run: |
         set -e
+        
+        echo "::group:: Creating package-info.json from PackageInfo.g"
         gap -A -q ${{ github.action_path }}/pkginfo_to_json.g
-        # TODO: Throw error if file was not made
+        if [ ! -f "package-info.json" ] ; then
+            echo "Could not create package-info.json"
+            exit 1
+        fi
 
     - name: "Read data from package-info.json"
       shell: bash
       run: |
         set -e
-        # Get necessary info from package-info.json
-
+        
+        echo "::group:: Extracting necessary information from package-info.json"
         TMP=($(cat package-info.json | jq -r '.ArchiveURL' | tr "/" " "))
         if [ "${#TMP[@]}" -eq 8 ] &&
            [ "${TMP[0]}" = "https:" ] &&
@@ -35,20 +48,19 @@ runs:
             echo "TAG=${TMP[6]}" >> "$GITHUB_ENV"
             echo "BASENAME=${TMP[7]}" >> "$GITHUB_ENV"
         else
-            # TODO: Should probably throw error here
-            echo "Problem with ArchiveURL"
+            echo "ArchiveURL in PackageInfo.g does not point to a GitHub release"
+            exit 1
         fi
-        echo "PKG=$(cat package-info.json | jq -r '.PackageName')" >> "$GITHUB_ENV"
+        echo "PKGNAME=$(cat package-info.json | jq -r '.PackageName')" >> "$GITHUB_ENV"
         echo "VERSION=$(cat package-info.json | jq -r '.Version')" >> "$GITHUB_ENV"
-        echo "DATE=$(cat package-info.json | jq -r '.Date')" >> "$GITHUB_ENV"
         echo "ARCHIVE_FORMATS=$(cat package-info.json | jq -r '.ArchiveFormats' | tr "," " ")" >> "$GITHUB_ENV"
         echo "DOCS=$(cat package-info.json | jq -r '.PackageDoc[].PDFFile' | tr "\n" " ")" >> "$GITHUB_ENV"
-        echo "ASSETS=package-info.json" >> "$GITHUB_ENV"
 
-    - name: "Cleanup before making a tarball"
+    - name: "Cleanup before making archives"
       shell: bash
       run: |
          set -e
+         
          echo "::group:: Cleanup git and github related files"
          rm -rvf .git* .hg* .cvs* .circleci
          rm -fv .codecov.* .travis.* .appveyor.* azure-pipelines.*
@@ -65,12 +77,13 @@ runs:
       shell: bash
       run: |
         set -e
-        # Move necessary files to subfolder
+        
+        echo "::group:: Moving package files to subfolder"
         shopt -s extglob
         mkdir -p "$BASENAME"
         mv !($BASENAME|package-info.json) $BASENAME
         
-        # Make archives
+        echo "::group:: Creating archives"
         for EXT in $ARCHIVE_FORMATS ; do
             ARCHIVENAME=$BASENAME$EXT
             FULLNAME="$PWD/$ARCHIVENAME"
@@ -80,39 +93,43 @@ runs:
             .tar.bz2) tar cf - "$BASENAME" | bzip2 -9c > "$ARCHIVENAME" ;;
             .zip)     zip -r9 --quiet "$ARCHIVENAME" "$BASENAME" ;;
             *)
-                # TODO: Should probably throw error here
-                echo "unsupported archive format $EXT"
-                continue
+                echo "Unsupported archive format $EXT"
+                exit 1
                 ;;
             esac
             if [ ! -f "$FULLNAME" ] ; then
-                # TODO: Should probably throw error here
-                echo "failed creating $FULLNAME"
-            else
-                echo "created $FULLNAME"
-                ASSETS="$ASSETS,$FULLNAME"
+                echo "Failed at creating $FULLNAME"
+                exit 1
             fi
+            echo "Created $FULLNAME"
         done
-        echo "ASSETS=$ASSETS" >> "$GITHUB_ENV"
 
-    - name: "Make copy of manual(s)"
+    - name: "Copy manual(s)"
       shell: bash
       run: |
         set -e
-        for DOC in $DOCS ; do
-            cp $BASENAME/$DOC $(basename $DOC)
-            ASSETS="$ASSETS,$(basename $DOC)"
-        done
-        echo "ASSETS=$ASSETS" >> "$GITHUB_ENV"
 
-    - name: "Make release"
+        echo "::group:: Copying manuals"
+        for DOC in $DOCS ; do
+            DOCFILE=$(basename $DOC)
+            cp $BASENAME/$DOC $DOCFILE
+            if [ ! -f "$DOCFILE" ] ; then
+                echo "Failed at copying $FULLNAME"
+                exit 1
+            fi
+        done
+
+    - name: "Make GitHub release"
       uses: softprops/action-gh-release@v2
-      if: startsWith(github.ref, 'refs/tags/')
+      if: ${{ inputs.dry-run == 'false' }}
       with:
-        body: "Release for ${{ env.PKG }}"
-        name: "${{ env.PKG }} ${{ env.VERSION }}"
-        draft: false
-        prerelease: false
+        body: "Release for ${{ env.PKGNAME }}"
+        name: "${{ env.PKGNAME }} ${{ env.VERSION }}"
         fail_on_unmatched_files: true
         tag_name: "${{ env.TAG }}"
-        files: "${{ env.ASSETS }}"
+        files: |
+          package-info.json
+          *.tar.gz
+          *.tar.bz2
+          *.zip
+          *.pdf
