Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -18,6 +18,20 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: "Validate input"
+      shell: bash
+      run: |
+        validate_boolean() {
+          local input=$1
+          local option_name=$2
+          if ! [[ "$input" =~ ^(true|false)$ ]]; then
+            echo "::error::Invalid value for option $option_name. Expected 'true' or 'false', but found '$input'"
+            exit 1;
+          fi
+        }
+
+        validate_boolean "${{ inputs.dry-run }}" dry-run
+        validate_boolean "${{ inputs.force }}" force
 
     - name: "Validate PackageInfo.g"
       shell: bash
@@ -52,8 +66,8 @@ runs:
       run: |
         gap -A -q $GITHUB_ACTION_PATH/pkginfo_to_json.g
         if [ ! -f "package-info.json" ] ; then
-            echo "::error::Could not create package-info.json"
-            exit 1
+          echo "::error::Could not create package-info.json"
+          exit 1
         fi
         mv package-info.json $ASSETS
 
@@ -67,11 +81,11 @@ runs:
            [ "${TMP[1]}" = "github.com" ] &&
            [ "${TMP[4]}" = "releases" ] &&
            [ "${TMP[5]}" = "download" ]; then
-            echo "TAG=${TMP[6]}" | tee -a "$GITHUB_ENV"
-            echo "BASENAME=${TMP[7]}" | tee -a "$GITHUB_ENV"
+          echo "TAG=${TMP[6]}" | tee -a "$GITHUB_ENV"
+          echo "BASENAME=${TMP[7]}" | tee -a "$GITHUB_ENV"
         else
-            echo "::error::ArchiveURL in PackageInfo.g does not point to a GitHub release"
-            exit 1
+          echo "::error::ArchiveURL in PackageInfo.g does not point to a GitHub release"
+          exit 1
         fi
         echo "PKGNAME=$(cat package-info.json | jq -r '.PackageName')" | tee -a "$GITHUB_ENV"
         echo "VERSION=$(cat package-info.json | jq -r '.Version')" | tee -a "$GITHUB_ENV"
@@ -132,15 +146,15 @@ runs:
       shell: bash
       working-directory: ${{ runner.temp }}/${{ env.BASENAME }}
       run: |
-         echo "::group::Cleanup git and github related files"
-         rm -rvf .git* .hg* .cvs* .circleci
-         echo "::group::Cleanup codecov, travis, azure-pipelines"
-         rm -fv .codecov.* .travis.* .appveyor.* azure-pipelines.*
-         rm -fv .gaplint.*
-         rm -fv requirements.txt
+        echo "::group::Cleanup git and github related files"
+        rm -rvf .git* .hg* .cvs* .circleci
+        echo "::group::Cleanup codecov, travis, azure-pipelines"
+        rm -fv .codecov.* .travis.* .appveyor.* azure-pipelines.*
+        rm -fv .gaplint.*
+        rm -fv requirements.txt
 
-         echo "::group::Cleanup macOS metadata"
-         find . -name .DS_Store -exec rm -f {} +
+        echo "::group::Cleanup macOS metadata"
+        find . -name .DS_Store -exec rm -f {} +
 
     - name: "Run autogen.sh"
       shell: bash
@@ -176,22 +190,22 @@ runs:
       working-directory: ${{ runner.temp }}
       run: |
         for EXT in $ARCHIVE_FORMATS ; do
-            ARCHIVENAME=$BASENAME$EXT
-            echo "Creating $ARCHIVENAME ..."
-            case $EXT in
+          ARCHIVENAME=$BASENAME$EXT
+          echo "Creating $ARCHIVENAME ..."
+          case $EXT in
             .tar.gz)  tar cf - "$BASENAME" | gzip -9c > "$ASSETS/$ARCHIVENAME" ;;
             .tar.bz2) tar cf - "$BASENAME" | bzip2 -9c > "$ASSETS/$ARCHIVENAME" ;;
             .zip)     zip -r9 --quiet "$ASSETS/$ARCHIVENAME" "$BASENAME" ;;
             *)
-                echo "::error::Unsupported archive format $EXT"
-                exit 1
-                ;;
-            esac
-            if [ ! -f "$ASSETS/$ARCHIVENAME" ] ; then
-                echo "::error::Failed at creating "$ARCHIVENAME""
-                exit 1
-            fi
-            echo "Created $ARCHIVENAME"
+              echo "::error::Unsupported archive format $EXT"
+              exit 1
+              ;;
+          esac
+          if [ ! -f "$ASSETS/$ARCHIVENAME" ] ; then
+            echo "::error::Failed at creating '$ARCHIVENAME'"
+            exit 1
+          fi
+          echo "Created $ARCHIVENAME"
         done
 
     - name: "Copy manual(s)"
