Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -79,14 +79,25 @@ jobs:
         shell: bash
         working-directory: ${{ runner.temp }}
         run: |
-          echo "--- 1. ---"
-          ls -a ./v1
-          echo "--- 2. ---"
-          ls -a ./v2
-          ARCHIVE="${PKGNAME}-${VERSION}"
-          sha256sum v1/${ARCHIVE}.zip     v2/${ARCHIVE}.zip
-          sha256sum v1/${ARCHIVE}.tar.gz  v2/${ARCHIVE}.tar.gz
-          sha256sum v1/${ARCHIVE}.tar.bz2 v2/${ARCHIVE}.tar.bz2
+          for EXT in .tar.gz .tar.bz2 .zip; do
+            f1="v1/${ARCHIVE}${EXT}"
+            f2="v2/${ARCHIVE}${EXT}"
+
+            # Skip if archive format doesn't exist
+            [[ -f "$f1" && -f "$f2" ]] || continue
+          
+            chk1=$(sha256sum "$f1" | cut -d' ' -f1)
+            chk2=$(sha256sum "$f2" | cut -d' ' -f1)
+          
+            if [[ "$chk1" != "$chk2" ]]; then
+              echo "::error::Mismatch for ${EXT} archives"
+              echo "v1: $chk1"
+              echo "v2: $chk2"
+              exit 1
+            else
+              echo "${EXT} archives are reproducible"
+            fi
+          done
 
   test-scripts:
     name: "Test the scripts used by this action"
